#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "🚀 Running pre-commit checks..."
echo "📝 Formatting and linting staged files..."
npx lint-staged

echo "🧪 Running tests..."
yarn test

echo "✅ All pre-commit checks passed!"
