#!/usr/bin/env sh

echo "🧐 Running pre-commit checks..."
echo "📝 Formatting and linting staged files..."
npx lint-staged

echo "🔍 Type checking..."
yarn type-check

echo "🧪 Running tests..."
yarn test

echo "✅ All pre-commit checks passed!"
